version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      # - sed -e "s/LOKI_URL/$LOKI_URL/g" ./fluent.conf

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_NAME .
      - docker build -t  loki  -f ../docker/Dockerfile

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag $IMAGE_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - echo Pushing Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - docker tag loki:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/loki:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/loki:$IMAGE_TAG
      # - sed -i "s/LOKI_URL/$LOKI_URL/g" ./fluent.conf

      # - echo $LOKI_URL > ./fluent.conf
      # - echo docker-compose build...
      # - docker-compose -f ./docker-compose.yml build
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/grafana:$IMAGE_TAG

      # - docker -f ./docker-compose.yml tag grafana/fluent-plugin-loki:main $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/grafana:$IMAGE_TAG
      # - docker-compose -f ./docker-compose.yml push fluentd $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:flunetd
